"""Estimate sheet fields + line items

Revision ID: a751120aa9cb
Revises: 
Create Date: 2026-02-15 14:58:55.466081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751120aa9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('material_price', sa.Float(), nullable=True),
    sa.Column('labor_price', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_line_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_line_item_job_id'), ['job_id'], unique=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_1', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cell', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('completed_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pickup_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('needed_by_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('approval_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inspected_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inspected_by', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('mfd_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_make', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('vehicle_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('vin', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('unit_number', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('proof_number', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('proof_approved_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('size_location_proof', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('work_order', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('crown_rep', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('summary_of_work', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shipping_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ship_to', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pickup_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('field_service_location', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('field_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('materials_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('labor_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sales_tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_handling', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('grand_total', sa.Float(), nullable=True))
        batch_op.alter_column('is_new',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('intake_order_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_job_intake_order_id'), ['intake_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_intake_order_id'))
        batch_op.alter_column('intake_order_id',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=40),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_new',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('grand_total')
        batch_op.drop_column('shipping_handling')
        batch_op.drop_column('sales_tax')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('labor_total')
        batch_op.drop_column('materials_total')
        batch_op.drop_column('field_charge')
        batch_op.drop_column('field_service_location')
        batch_op.drop_column('pickup_name')
        batch_op.drop_column('ship_to')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('shipping_type')
        batch_op.drop_column('shipping_date')
        batch_op.drop_column('internal_notes')
        batch_op.drop_column('summary_of_work')
        batch_op.drop_column('crown_rep')
        batch_op.drop_column('work_order')
        batch_op.drop_column('size_location_proof')
        batch_op.drop_column('proof_approved_date')
        batch_op.drop_column('proof_number')
        batch_op.drop_column('unit_number')
        batch_op.drop_column('vin')
        batch_op.drop_column('vehicle_model')
        batch_op.drop_column('vehicle_make')
        batch_op.drop_column('mfd_date')
        batch_op.drop_column('inspected_by')
        batch_op.drop_column('inspected_date')
        batch_op.drop_column('scheduled_date')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('needed_by_date')
        batch_op.drop_column('pickup_date')
        batch_op.drop_column('completed_date')
        batch_op.drop_column('cell')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_2')
        batch_op.drop_column('address_1')

    with op.batch_alter_table('job_line_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_line_item_job_id'))

    op.drop_table('job_line_item')
    # ### end Alembic commands ###
